apiVersion: v2
name: agents
description: A simple CAP project.
type: application
version: 1.0.0
appVersion: 1.0.0
annotations:
  app.kubernetes.io/managed-by: cds-dk/helm
dependencies:
  - name: web-application
    alias: srv
    version: ">0.0.0"
  - name: web-application
    alias: approuter
    version: ">0.0.0"
  - name: web-application
    alias: mcp-client
    version: ">0.0.0"
  # - name: web-application
  #   alias: portal
  #   version: ">0.0.0"

  - name: service-instance
    alias: destination
    version: ">0.0.0"
  - name: service-instance
    alias: identity
    version: ">0.0.0"
  # - name: service-instance
  #   version: ">0.0.0"
  #   alias: "postgresql"
